version: '3.7'
services:
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  node-exporter:
    image: node-exporter
  redis-exporter:
    image: oliver006/redis_exporter
    command: ["--redis.addr=redis:6379"]
  prometheus:
    image: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/data
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--storage.tsdb.path=/data",
    ]
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
volumes:
  redis-data:
  prometheus-data:
  grafana-data:
