global:
   scrape_interval: 15s
   scrape_timeout: 10s
   evaluation_interval: 15s
   external_labels:
      instance_name: $(hostname)
scrape_configs:
   job_name: node-exporter
      static_configs:
         targets: node-exporter:9100
   job_name: redis-exporter
      static_configs:
         targets: redis-exporter:9121
      metric_relabel_configs:
         source_labels: [__name__]
         target_label: __name__
         regex: "(redis_.*_id[1-8])"
         action: keep
         source_labels: [instance]
         target_label: instance
         replacement: "$(instance_name)"
